apiVersion: v2
name: nma-mysql
description: A Helm chart to install mysql
type: application
version: 8.0.29
appVersion: 8.0.29

dependencies:
- name: mysql
  repository: https://charts.bitnami.com/bitnami
  version: 14.0.4
